# Generated by Django 5.2.8 on 2025-11-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_remove_event_created_by_remove_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start_time'], 'verbose_name': 'Доклад', 'verbose_name_plural': 'Доклады'},
        ),
        migrations.RemoveField(
            model_name='talk',
            name='order',
        ),
    ]
