# Generated by Django 5.2.8 on 2025-11-28 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_user_is_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема доклада')),
                ('description', models.TextField(verbose_name='Описание доклада')),
                ('duration', models.PositiveIntegerField(help_text='Рекомендуется 15-45 минут', verbose_name='Продолжительность (мин)')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Заметки организатора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_applications', to='app_core.user')),
            ],
            options={
                'verbose_name': 'Заявка спикера',
                'verbose_name_plural': 'Заявки спикеров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
