# Generated by Django 5.2.8 on 2025-11-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_speakerapplication_delete_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='app_core.event'),
        ),
    ]
