# Generated by Django 5.2.8 on 2025-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_alter_donation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
    ]
