# Generated by Django 5.2.8 on 2025-11-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_event_notification_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок рассылки')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('sent_to_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено пользователям')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок отправки')),
                ('target_users', models.CharField(choices=[('all', 'Все подписанные'), ('custom', 'Выбранные пользователи')], default='all', max_length=20, verbose_name='Целевые пользователи')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('custom_users', models.ManyToManyField(blank=True, help_text='Выберите конкретных пользователей для рассылки', to='app_core.user', verbose_name='Выбранные пользователи')),
            ],
            options={
                'verbose_name': 'Массовая рассылка',
                'verbose_name_plural': 'Массовые рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
