# Generated by Django 5.2.8 on 2025-11-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_massnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_sent_day',
            field=models.BooleanField(default=False, verbose_name='Напоминание за день отправлено'),
        ),
        migrations.AddField(
            model_name='event',
            name='notification_sent_week',
            field=models.BooleanField(default=False, verbose_name='Напоминание за неделю отправлено'),
        ),
    ]
