# Generated by Django 5.2.8 on 2025-11-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_event_notification_sent_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя для знакомств')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Компания')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('interests', models.TextField(verbose_name='Интересы и темы для общения')),
                ('contact_consent', models.BooleanField(default=False, verbose_name='Согласие на обмен контактами')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость в поиске')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networking_profile', to='app_core.user')),
            ],
            options={
                'verbose_name': 'Анкета знакомств',
                'verbose_name_plural': 'Анкеты знакомств',
            },
        ),
        migrations.CreateModel(
            name='NetworkingInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('viewed', 'Просмотрено'), ('liked', 'Понравилось'), ('rejected', 'Отклонено'), ('matched', 'Взаимный интерес')], default='viewed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_profiles', to='app_core.user')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app_core.networkingprofile')),
            ],
            options={
                'verbose_name': 'Взаимодействие знакомств',
                'verbose_name_plural': 'Взаимодействия знакомств',
                'unique_together': {('viewer', 'profile')},
            },
        ),
    ]
