# Generated by Django 5.2.8 on 2025-11-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_networkingprofile_networkinginteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkingprofile',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Username для контактов'),
        ),
    ]
