# Generated by Django 5.2.8 on 2025-11-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0009_networkingprofile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkingMatch',
        ),
    ]
